default:
  default_args:
    start_date: "2025-02-01"

add_your_dag_name_here_dag:
  default_args:
    owner: "add_your_name_here"
  description: "add your description here"
  tags:
    - "dag_factory"
  catchup: false
  schedule_interval: "0 0 * * *"
  task_groups:
    ml:
      tooltip: "this is a ml task group"
  tasks:
    bash_demo:
      operator: airflow.operators.bash.BashOperator
      bash_command: "${AIRFLOW_HOME}/scripts/example_script"
    preprocess_task:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.preprocess
      task_group_name: ml
      dependencies: [ bash_demo ]
    train_task:
      operator: airflow.operators.python.PythonOperator
      python_callable: {{ cookiecutter.package_name }}.train
      task_group_name: ml
      dependencies: [ preprocess_task ]
