name: {{ cookiecutter.folder_name }}
channels:
  - conda-forge
dependencies:
  # required for mlops framework
  - python >3.10,<3.13
  - mlflow
  - psycopg2-binary
  - boto3
  - airflow
  - apache-airflow-providers-cncf-kubernetes
  - jupyter
  - python-dotenv
  - git
  - pip
  - pip:
    - dag_factory
  # This is only needed for an exmaple. If you dont need this, please feel free to remove it.
  - keras
  - tensorflow
  - numpy =2.0.2
  # Testing
  - pytest-cov
  - pytest
  # add your libraries here
